### PR TITLE
Update to version 0.8.3

### PR DESCRIPTION
**Pull request by m-rossi**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by m-rossi** [comment]
@conda-forge-admin, please rerender

**Comment by m-rossi** [comment]
Damn, forgot to check if quickjs is available on conda-forge

**Comment by fcollonval** [comment]
Thanks for starting this @m-rossi 

Do you plan to create a recipe for quickjs Python binding?

I think it is not gonna be too hard to achieve.

The only part that certainly needs to be patch is that condition on windows: https://github.com/PetterS/quickjs/blob/a2d23c021a6d3dc4895f4cf87729d5f17412939e/setup.py#L10

If you create a PR in [conda-forge/staged-recipes](https://github.com/conda-forge/staged-recipes), feel free to add me as maintainer. I have some experience with advanced conda recipes.

**Comment by m-rossi** [comment]
> Do you plan to create a recipe for quickjs Python binding?
> 
> I think it is not gonna be too hard to achieve.
> 
> The only part that certainly needs to be patch is that condition on windows: https://github.com/PetterS/quickjs/blob/a2d23c021a6d3dc4895f4cf87729d5f17412939e/setup.py#L10
> 
> If you create a PR in [conda-forge/staged-recipes](https://github.com/conda-forge/staged-recipes), feel free to add me as maintainer. I have some experience with advanced conda recipes.

@fcollonval Yes, that's planned for later today. Thank you for mentioning the Windows condition, I will look into that when creating the recipe and add you as a maintainer.

I have also seen that `px-proxy` also seems to work on Linux and macOS, too. Especially on Linux we need to add some additional packages on conda-forge, too. But that's a later, additional step.

**Comment by fcollonval** [comment]
> I have also seen that px-proxy also seems to work on Linux and macOS, too. Especially on Linux we need to add some additional packages on conda-forge, too. But that's a later, additional step.

I agree updating it will already be a great achievement.

**Comment by m-rossi** [comment]
@conda-forge-admin, please rerender

**Comment by m-rossi** [comment]
Not fully working, `px --help` returns
```
Requires libcurl
  Download from https://curl.se/windows and extract DLLs to px/libcurl
```

**Comment by fcollonval** [comment]
Thanks for pushing on this @m-rossi 

It seems px code source will need to be patched due to those lines:

https://github.com/genotrance/px/blob/faaa57c2e7bd06f1bc502e8a1d63b6911a667c27/px/libcurl/_platform/_windows/__init__.py#L22-L23

I checked the `libcurl` conda package it contains only a `libcurl.dll` file (targeting win 64bits).

**Comment by m-rossi** [comment]
@fcollonval This is ready for review.

**Review by fcollonval — APPROVED** [review]
Thanks a lot @m-rossi 

Would you be willing to become a maintainer of this package? If yes, feel free to add you to the maintainer list.

**Comment by m-rossi** [comment]
Sure, one feedstock more or less also no longer makes a difference 😅

**Review by fcollonval — APPROVED** [review]

**Pull request merged**
